spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gbr_prototype?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    user: musheghgh
    password: Aa!812483al
    url: jdbc:mysql://localhost:3306
    schemas: gbr_prototype
server:
  port: 8081