spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gbr_prototype?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8081